server:
  port: 80
  servlet:
    context-path:
#自定义参数配置
custom:
  value1: 测试参数1
spring:
  datasource:
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      #设置默认的数据源或者数据源组,默认值即为master
      primary: test_1
        #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      strict: true
      datasource:
        test_1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/database1?serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8
          username: user1
          password: password1
        test_2:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/database1?serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8
          username: user1
          password: password1
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB
  thymeleaf:
    encoding: utf-8
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML
  application:
    name: springboot_study
  mvc:
    view:
      prefix: /
      suffix: .jsp
#mybatis:
#  mapper-locations:
#    classpath*:com/jdw/springboot/mapper/sqlxml/*.xml
#  type-aliases-package: com.jdw.bean
#  #  配置mybatis开启驼峰命名
#  configuration:
#    map-underscore-to-camel-case: true
#    #打印mybatis所有SQL执行
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  global-config:
    db-config:
      #全局逻辑删除字段名，实体配置了 @TableLogic 则以实体的为准，未配置则默认 status 为逻辑删除字段
      logic-delete-field: status
      #逻辑删除值 0
      logic-delete-value: 0
      #逻辑未删除值 1
      logic-not-delete-value: 1
  #通用枚举类扫描 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.jdw.springboot.enums
  configuration:
    #打印 sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#配置简单请求路径
simple-view-controllers:
  views:
  - view-name: user/ordinary
    url: /forgetPsd
  - view-name: user/admin
    url: /iregister
  - view-name: user/boss
    url: /boss